### ISSUE TITLE
wasm32-unknown-unknown is broken

### ISSUE THREAD

**Issue by nagisa** [rust-lang/stacker#15]
cc @pepyakin 

Attempting to run tests for wasm32 fails with an error like this:

```
  = note: rust-lld: error: /home/runner/work/stacker/stacker/src/arch/wasm32/libstacker.a: Unexpected metadata version: 1 (Expected: 2)
```

(see [here](https://github.com/rust-lang/stacker/runs/249188250)) but I also failed to re-generate the `libstacker.a`:

```
stack_pointer.s:9:2: error: invalid instruction
        get_global      __stack_pointer@GLOBAL
        ^
switch_stacks.s:14:2: error: invalid instruction
        get_global      __stack_pointer@GLOBAL
        ^
switch_stacks.s:17:2: error: invalid instruction
        get_local       0
        ^
switch_stacks.s:18:2: error: invalid instruction
        set_global      __stack_pointer@GLOBAL
        ^
switch_stacks.s:21:2: error: invalid instruction
        get_local       2
        ^
switch_stacks.s:22:2: error: invalid instruction
        get_local       1
        ^
switch_stacks.s:26:2: error: invalid instruction
        set_global      __stack_pointer@GLOBAL
        ^
```

I made a couple attempts to rectify the issues here, but in the end I just ended up with

```
lld: error: switch_stacks.o: Bad relocation data index
```

---

(I also see little benefit in supporting this particular target, as the implementation does not do what one would expect from this library *anyway*; and given that this is broken for the past half a year, I don’t think anybody needs what support exists either)

**Comment by pepyakin** [comment]
We ended up not using this for our project for now and TBH it is not clear if we ever will, so I am ok with dropping this target.

However, if needed I can give a shot to this issue as well

**Comment by nagisa** [comment]
It is fine, I’ll remove the code for now and we can add it back if anybody needs it again.

Thanks!
