### ISSUE TITLE
Please update the license files in the psm subdirectory

### ISSUE THREAD

**Issue by silwol** [rust-lang/stacker#29]
In my attempt to package `psm` for Debian, I took a look at the licensing of the crate. According to the git history, you recently changed the license from `ISC/Apache-2.0` to `MIT/Apache-2.0`. The `LICENSE-ISC` file is still present, while there `LICENSE-MIT` file present. In the Debian project, we have rather strict checks for consistency of the licensing situation, so in order to prevent any ambiguity and unnecessary discussion, it would help us if you could update the licensing files in the `psm` crate to reflect the licensing correctly. Thanks a lot in advance!

**Comment by silwol** [comment]
Oh, I just saw that a pull request for this change already exists. It would be perfect for us if that is merged.

**Comment by nagisa** [comment]
Is it necessary for you to have a release in crates.io with the updated license? Are you fine with waiting an unknown amount of time for it to accumulate more changes?

**Comment by nagisa** [comment]
Done in https://github.com/rust-lang/stacker/commit/c0098c525d54a54dcd1b87cd203220f44cab1dab.

**Comment by silwol** [comment]
I don't think it's necessary to release it extra for this change, unless it takes a very long time until you'd do one. Thanks for the fast fix.
