### ISSUE TITLE
psm: armasm.asm files still being compiled despite marked as false?

### ISSUE THREAD

**Issue by Stammark** [rust-lang/stacker#35]
Hi there! I'm new here, and to Rust, so bear with and lmk if I've misread anything!

So, I've been experimenting with the aarch64-pc-windows-msvc target, and have come across a little problem with this crate:

Am I right in reading that for targets marked as "false" in psm/build.rs, that psm is effectively disabled and the code in the .asm files would never actually be run?

If that code can never be linked & run for these targets, is it a bug that the .asm files are compiled to .o?

For context: I noticed this because a reference to this crate was recently added to rustc, and I am seeing a problem when armasm64.exe attempts to assemble aarch64_armasm.asm (am looking into this rn).

Cheers!
Stam

**Comment by nagisa** [comment]
You are probably referring to `false/true` in this table: 

https://github.com/rust-lang/stacker/blob/master/psm/build.rs#L9

The `false` here means just that the implementations for _switching_ the stack are not (yet) valid. However the assembly files also contain code to obtain the current stack pointer and the stack direction as well, so they will be compiled either way, regardless of true or false in the table.

All of the assembly files are written to be valid and linkable assembly. Is that not the case?

**Comment by Stammark** [comment]
Aha, I see, thank you so much for the info. And yes, I was a bit hasty in raising this, sorry! 

So, my problem with not being able to compile: It turns out this was coming from the cc-rs crate giving bad compiler flags to armasm64. I'll patch this in cc-rs.

I have successfully compiled and linked now and I then get a Windows 0xc0000005 status_access_violation error when I try to run a `cargo test`. However, this is just as likely to be due to my experimental compiler or Windows, since your assembler looks harmless enough :)

Maybe we can close this issue and if I do find a problem later, I'll raise it specifically!

**Comment by nagisa** [comment]
Please do! Thanks!
