### ISSUE TITLE
Unchecked error

### ISSUE THREAD

**Issue by jD91mZM2** [rust-lang/stacker#39]
Stacker seems to cause a segfault when trying to run rustc on Redox OS, see [this issue](https://github.com/bjorn3/rustc_codegen_cranelift/issues/1059).

I'm not 100% why, but I noticed [this unchecked sysconf(...) invocation](https://github.com/rust-lang/stacker/blob/93325b418f6ae0f496efb6dcad0c9e97e09d5cf7/src/lib.rs#L144-L150). On Redox OS, `libc::sysconf(libc::_SC_PAGE_SIZE)` will always result in the errno `EINVAL` and the return value -1, which is correct according to the manual.

`(-1) as usize` is, of course, `usize::MAX`, so I'm not sure why the following `.expect` call isn't causing a panic. But somehow, stacker incorrectly seems to decide to grow the stack, which further causes some issue in rustc_codegen_cranelift(?)

**Comment by bjorn3** [comment]
When using a cg_clif compiled rustc on Linux, stacker almost never decides that it needs to grow the stack, thus causing no problems. However on Redox OS, it does unnecessarily decide that the stack needs to grow. For this it calls a asm function. This is causing problems as there is probably an abi incompatibility in cg_clif with the SysV abi that the asm function expectd, thus causing a crash.

**Comment by nagisa** [comment]
> (-1) as usize is, of course, usize::MAX, so I'm not sure why the following .expect call isn't causing a panic.

Very curious. We can and should fix the unchecked return, but `.expect` not failing further along is a pretty clear indication to me that at least in this specific case the `sysconf` call is not what's failing here. The only failure mode of `sysconf` is `EINVAL name is invalid.` so it failing would indicate a wrong `_SC_PAGE_SIZE` constant value for the platform.

> I think this is because stacker doesn't know how to get the stack limit on Redox OS and thus always tries to increase the stack size.

Note that this will happen the first time stacker is invoked only. After the first time a new stack is allocated, stacker caches this information and will not re-allocate stack unnecessarily anymore.

So some sort of an ABI mismatch sounds most plausible to me. https://github.com/rust-lang/stacker/blob/0fd32d4c195b4f2b78d00d74d8991eed44e67407/psm/src/arch/x86_64.s#L72 is most likely the function failing. https://github.com/rust-lang/stacker/blob/0fd32d4c195b4f2b78d00d74d8991eed44e67407/psm/src/lib.rs#L74 is then its `extern` declaration.

If the build of rustc fails, it is likely that `psm` and `stacker` tests will fail much the same way so I’d probably start by running those, just to reduce the scope with which we're dealing here (though I guess there's a chicken-and-egg problem of how to run the tests here if we don't have a full toolchain... one way could be to just return `false` [here](https://github.com/rust-lang/stacker/blob/master/psm/build.rs#L3) for the rustc build…)

**Comment by jD91mZM2** [comment]
You're right, @bjorn3 found out that `rust_psm_on_stack` is indeed the function failing :)

**Comment by nagisa** [comment]
Is this still an issue that needs tracking?

**Comment by jD91mZM2** [comment]
I'm not sure if there has been any progress with rustc on Redox OS, but I absolutely think we can close this issue as it's likely our fault (as you say, an ABI mismatch).
