### ISSUE TITLE
Linking failing when compiling for wasm32-wasi

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/stacker#41]
```
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "wasm" [...] "-l" "stacker" "-l" "psm_s"
  = note: rust-lld: error: unable to find library -lstacker
          rust-lld: error: unable to find library -lpsm_s
```

**Comment by nagisa** [comment]
Huh, the CI actually even runs tests for the wasm32-wasi target as added in #40.

**Comment by nagisa** [comment]
Please do provide more information either way.

**Comment by nagisa** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
This was the error I was getting before #40, can you confirm that you're using versions with #40 in them?

**Comment by bjorn3** [comment]
With `psm 0.1.11` and `stacker 0.1.10` it works fine.
