### ISSUE TITLE
Incorrect cc dependency

### ISSUE THREAD

**Issue by kornelski** [rust-lang/stacker#52]
The `psm` crate asks for `cc = "1.0"`, but it's not compatible with this version of `cc`:

> no method named `is_like_msvc` found for type `cc::Tool` in the current scope

**Comment by nagisa** [comment]
I'll look into adding a CI job for `-Zminimal-versions` this week.

**Comment by kornelski** [comment]
BTW, I'm currently batch-testing crates using `-Zminimal-versions` and… everything's broken. Don't get discouraged if it won't be usable in CI yet. There are many popular crates that don't specify their deps correctly, and `-Zminimal-versions` being recursive is too good at finding these problems.

**Comment by nagisa** [comment]
This should be fixed in the newly released versions.
