### ISSUE TITLE
Support for platforms other than *86

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [rust-lang/stacker#64]
This crate is the shortest path to solving a stack size issue I have, but unfortunately it does not compile for armv7.
Would be great if further platforms are also supported.

**Comment by nagisa** [comment]
This is not an useful issue without more information, especially because we do have code in place to support all sorts of 32-bit ARM implementations that can utilize either the GAS or the armasm assembler.

**Comment by nagisa** [comment]
I'll close this for now. Please file a new issue with more information.
